name: empty
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  flutter_svg: ^1.1.6 #^0.22.0
  cached_network_image: ^3.2.1 #3.2.0
  flutter_bloc: ^7.0.0
  json_serializable: ^6.3.1 #^4.1.1
  animated_floating_buttons: ^0.0.2
  floating_action_bubble: ^1.1.4
  textfield_tags: ^2.0.2
  emoji_picker_flutter: ^1.5.4
  flutter_gradient_colors: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/localization/en.json
    - assets/images/
    - assets/icons/
    - assets/
    - assets/icons/send.png
    - assets/tutorial/swipe-up-colored.png

